##
##  k8s-util -- Kubernetes (K8S) Utility
##  Copyright (c) 2019-2021 Dr. Ralf S. Engelschall <rse@engelschall.com>
##
##  Permission is hereby granted, free of charge, to any person obtaining
##  a copy of this software and associated documentation files (the
##  "Software"), to deal in the Software without restriction, including
##  without limitation the rights to use, copy, modify, merge, publish,
##  distribute, sublicense, and/or sell copies of the Software, and to
##  permit persons to whom the Software is furnished to do so, subject to
##  the following conditions:
##
##  The above copyright notice and this permission notice shall be included
##  in all copies or substantial portions of the Software.
##
##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
##  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
##  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
##  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
##  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
##  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
##  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

%!namespace
---
#   create "{{ns}}" namespace
apiVersion: v1
kind: Namespace
metadata:
    name: {{ns}}
    labels:
        name: {{ns}}

%!cluster-admin
---
#   create "{{sa}}" cluster service account
apiVersion: v1
kind: ServiceAccount
metadata:
    namespace: {{ns}}
    name: {{sa}}
    labels:
        name: {{sa}}
---
#   create full-access role for cluster service account "{{sa}}"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    namespace: {{ns}}
    name: {{sa}}-role
    labels:
        name: {{sa}}
rules:
    -   apiGroups: [ "", "*" ]
        resources: [ "*" ]
        verbs: [ "*" ]
---
#   bind full-access role to cluster service account "{{sa}}"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    namespace: {{ns}}
    name: {{sa}}-role-binding
    labels:
        name: {{sa}}
subjects:
    -   kind: ServiceAccount
        namespace: {{ns}}
        name: {{sa}}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{sa}}-role

%!namespace-admin
#   create "{{sa}}" service account in "{{ns}}" namespace
apiVersion: v1
kind: ServiceAccount
metadata:
    namespace: {{ns}}
    name: {{sa}}
    labels:
        name: {{sa}}
---
#   create full-access role for service account "{{sa}}" in "{{ns}}" namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: {{ns}}
    name: {{sa}}-role
    labels:
        name: {{sa}}
rules:
    -   apiGroups: [ "", "*" ]
        resources: [ "*" ]
        verbs: [ "*" ]
---
#   bind full-access role to service account "{{sa}}" in "{{ns}}" namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    namespace: {{ns}}
    name: {{sa}}-role-binding
    labels:
        name: {{sa}}
subjects:
    -   kind: ServiceAccount
        namespace: {{ns}}
        name: {{sa}}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{sa}}-role

%!kubeconfig-stub
---
apiVersion: v1
kind: Config
current-context:
contexts:
clusters:
users:

%!kubeconfig
---
apiVersion: v1
kind: Config
current-context: {{context}}
contexts:
    -   name: {{context}}
        context:
            cluster: {{cluster}}
            namespace: {{ns}}
            user: {{cluster}}-{{sa}}
clusters:
    -   name: {{cluster}}
        cluster:
            server: {{server}}
users:
    -   name: {{cluster}}-{{sa}}
        user:
            token: {{token}}

